# -*- coding: utf-8 -*-
"""Copy of revisiPsd (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1plwRFM2cSkOM-MgcyvIBgAqU6YUMRK34

#DATA UNDERSTANDING

##Import Library
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import StandardScaler

"""##Load Data"""

dataset = pd.read_csv("dataset_2.csv")

"""##Melihat Sample Data"""

# Menampilkan 5 baris pertama data
dataset.head()

"""##Mengecek Dimensi Data"""

# Melihat jumlah baris dan kolom
dataset.shape

"""##Mengecek Tipe Data & Nilai Kosong"""

# Melihat informasi tipe data dan memori
dataset.info()

# Menghitung jumlah nilai yang hilang (NaN/Null) di setiap kolom
dataset.isnull().sum()

"""##Mengecek Data Duplikat"""

# Cek jumlah total data
print(f"Total Baris Data: {dataset.shape[0]}")

# Cek duplikasi
duplikat = dataset.duplicated().sum()
print(f"Jumlah Data Duplikat: {duplikat}")

"""##Eksplorasi Target"""

# Menghitung jumlah kategori pada kolom target
dataset['LUNG_CANCER'].value_counts()

# Visualisasi sebaran data target menggunakan diagram batang
sns.countplot(x='LUNG_CANCER', data=dataset)
plt.title('Target Distribution')
plt.show()

"""#DATA PREPROCESSING

##Menghapus Data Duplikat
"""

# Menghapus baris yang duplikat
dataset = dataset.drop_duplicates()

"""##Menghapus Kolom yang Tidak Digunakan"""

columns_to_drop = ['ANXIETY', 'PEER_PRESSURE', 'CHRONIC DISEASE',
                   'GENDER', 'AGE', 'ALCOHOL CONSUMING']
# Use 'dataset' as the source DataFrame, as 'df' might not be correctly initialized or contain these columns.
df_clean = dataset.drop(columns=columns_to_drop)

"""##Encoding"""

label_encoder = LabelEncoder()
dataset['LUNG_CANCER'] = label_encoder.fit_transform(dataset['LUNG_CANCER'])

"""##Transformasi Fitur (Mengubah nilai 1 & 2 menjadi 0 & 1)"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder

columns_to_transform = ['SMOKING', 'YELLOW_FINGERS', 'FATIGUE', 'ALLERGY',
                        'WHEEZING', 'COUGHING', 'SHORTNESS OF BREATH',
                        'SWALLOWING DIFFICULTY', 'CHEST PAIN']

print("Cek Data Setelah Preprocessing:")
print(dataset.head())

"""##Memisahkan Fitur (x) dan Target (y)"""

# X adalah semua kolom KECUALI 'LUNG_CANCER'
X = dataset.drop('LUNG_CANCER', axis=1)

# y adalah kolom 'LUNG_CANCER' saja
y = dataset['LUNG_CANCER']

"""##Membagi Data Latih dan Data Uji"""

from sklearn.model_selection import train_test_split

# Membagi data: 80% Training, 20% Testing
sc = StandardScaler()
label_encoder_gender = LabelEncoder()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

"""##Feature Scaling"""

from sklearn.preprocessing import StandardScaler, LabelEncoder

X_train['GENDER'] = label_encoder_gender.fit_transform(X_train['GENDER'])
X_test['GENDER'] = label_encoder_gender.transform(X_test['GENDER'])

# Menyesuaikan skala data training dan testing.
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

"""#MODELING

##Membuat dan Melatih Model KNN
"""

from imblearn.over_sampling import SMOTE

sm = SMOTE(random_state=42)
X_train_res, y_train_res = sm.fit_resample(X_train, y_train)

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x=y_train_res)
plt.title("Distribusi Setelah SMOTE")
plt.show()

from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
classifier.fit(X_train_res, y_train_res)   # pakai data hasil SMOTE

"""##Prediksi"""

# Memprediksi hasil test set
y_pred = classifier.predict(X_test)

"""##Evaluasi Model"""

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report, f1_score, precision_score, recall_score

# 1. Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# 2. Menghitung Akurasi (Accuracy)
acc = accuracy_score(y_test, y_pred)
print(f"\nAkurasi Model: {acc}")

# 3. Menampilkan Laporan Lengkap (Precision, Recall, F1-Score)
# classification_report otomatis menghitung metrik untuk setiap kelas (0 dan 1)
print("\nLaporan Klasifikasi Lengkap:")
print(classification_report(y_test, y_pred))

from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=3, metric='minkowski', p=2)
classifier.fit(X_train_res, y_train_res)   # pakai data hasil SMOTE

# Memprediksi hasil test set
y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report, f1_score, precision_score, recall_score

# 1. Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# 2. Menghitung Akurasi (Accuracy)
acc = accuracy_score(y_test, y_pred)
print(f"\nAkurasi Model: {acc}")

# 3. Menampilkan Laporan Lengkap (Precision, Recall, F1-Score)
# classification_report otomatis menghitung metrik untuk setiap kelas (0 dan 1)
print("\nLaporan Klasifikasi Lengkap:")
print(classification_report(y_test, y_pred))

from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=4, metric='minkowski', p=2)
classifier.fit(X_train_res, y_train_res)   # pakai data hasil SMOTE

# Memprediksi hasil test set
y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report, f1_score, precision_score, recall_score

# 1. Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# 2. Menghitung Akurasi (Accuracy)
acc = accuracy_score(y_test, y_pred)
print(f"\nAkurasi Model: {acc}")

# 3. Menampilkan Laporan Lengkap (Precision, Recall, F1-Score)
# classification_report otomatis menghitung metrik untuk setiap kelas (0 dan 1)
print("\nLaporan Klasifikasi Lengkap:")
print(classification_report(y_test, y_pred))